# Nome do projeto
spring.application.name=portfolio-api

# Ativa o perfil "local" para ler as senhas do outro arquivo
spring.profiles.active=local

# Configurações de Hibernate e JPA (Públicas)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Porta do Servidor
server.port=18065